language: php
php:
  - 5.4
  - 5.5
before_script:
  - composer self-update
  - composer install
  - export AURA_PROJECT_START_SERVER="0"
  - export AURA_PROJECT_SERVER_HOST="localhost:8080"
  - "php -S localhost:8080 -t web/ &"
  - cd tests/project
script: phpunit

