<?php

echo $this->form([
    'method' => $method,
    'action' => $action,
    'enctype' => "application/x-www-form-urlencoded",
    ]
);
    /**
     * @var \Gallery\Input\AlbumForm $albumForm
     */
echo $this->input(
    $albumForm->get("album")
);

echo $this->input([
    'type'    => "hidden",
    'name'    => "album[parent]",
    'value'   => $album->getId(),
]);

echo $this->input([
    'type' => 'submit',
    'name' => 'submit',
    'value' => $submit,
    ]
);

echo $this->tag('/form');