<?php
use Aura\Html\Escaper;

$this->title()->set("Images and albums");

if(count($this->albums) > 0): ?>
    <div class="clearfix">
    <?php foreach($this->albums as $album): ?>
        <div class="clearfix">
            <div class="col-xs-2 clearfix">
            <p>
                <a href="/gallery/albums/images/album/<?php echo Escaper::h($album->getId()); ?>">
                    <?php echo Escaper::h($album->getTitle()); ?>
                </a>
            </p>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif;
if(count($this->images) > 0): ?>
    <div class="clearfix">
    <?php foreach($this->images as $image): ?>
        <div class="col-xs-2 clearfix">
            <p>
                <a href="/gallery/albums/images/album/<?php echo Escaper::h($image->getId()); ?>">
                    <?php echo Escaper::h($image->getTitle()); ?>
                </a>
            </p>
        </div>
    <?php endforeach; ?>
    </div>
<?php endif; ?>
