<!DOCTYPE html>
<html>
<head>
    <?php echo $this->title(); ?>

    <link rel="stylesheet" href="/css/poole.css">
    <link rel="stylesheet" href="/css/syntax.css">

    <link rel="stylesheet" href="/css/hyde.css">
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/hyde-appendix.css">




    <!--    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">-->
</head>
<body>

<?php if ($this->hasSection('sidebarEdit')):
    echo $this->getSection('sidebarEdit');
else:
    echo $this->render('sidebarEdit');
endif; ?>
<div class="content container">
    <?php echo $this->getContent(); ?>
</div>
</body>
</html>