<div class="sidebar">
    <div class="sidebar-sticky">
        <div class="sidebar-about">
            <h2>Gallery</h2>
        </div>

        <nav class="sidebar-nav">
            <a class="sidebar-nav-item" href="<?php echo $this->router()->generate('gallery_edit'); ?>">Edit Gallery</a>
            <a class="sidebar-nav-item" href="<?php echo $this->router()->generate('images_form_upload'); ?>">New Image</a>
        </nav>
    </div>
</div>