<div class="sidebar">
    <div class="sidebar-sticky">
        <div class="sidebar-about">
            <h2>Edit Gallery</h2>
        </div>

        <nav class="sidebar-nav">
            <a class="sidebar-nav-item" href="<?php echo $this->router()->generate("gallery_root_albums"); ?>">Gallery</a>
            <a class="sidebar-nav-item" href="<?php echo $this->router()->generate("al"); ?>">Edit Album</a>
        </nav>

<!--        <div>-->
<!--            --><?php //echo $this->render("formAlbum"); ?>
<!--        </div>-->
    </div>
</div>